### ISSUE TITLE
💎 Refactor: Music, CollaboRequest Domain Refactoring

### ISSUE THREAD

**Issue by JeekLee** [ProjectBlueHair/FinalProject_BE#117]
## Description
Music, CollaboRequest Domain Refactoring

## Before
- Music Domain 내 일부 컨벤션을 미준수한 코드 존재
- Swagger에서 일부 CollaboRequest API의 Request Parameter가 정상적으로 명시되지 않음 

## After
Music Domain 컨벤션 적용 및 Swagger 정상 작동

## Todo
- [ ] Music Domain 내 컨벤션이 적용되지 않은 부분들 수정
- [ ] Music 관련 작업 후 꼬여버린 CollaboRequest Swagger 수정
- [ ] CollaboRequest Title Field 제거
